/user/profile/operations/last:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching the last bankings operations of an user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
/user/profile/operations/details:
  post:
    security:
      - Bearer: []
    tags:
      - User Module
    summary: User Profile API
    description: API for fetching the informations of a specitif operations
    parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        required: true
      - in: body
      operationsNumber: body
      required: true
    produces:
      - application/json
    responses:
      '200':
        description:  Operations retrieved successully
        schema:
          $ref: '#/definitions/ApiResponse'
      '400':
        description: Invalid Fields
      '500':
        description: Internal Server Error

  